### ISSUE TITLE
Typo in aurelia-loader-default.d.ts

### ISSUE THREAD

**Issue by laurentiustamate94** [cmichaelgraham/aurelia-amd-bundler#2]
https://github.com/cmichaelgraham/aurelia-amd-bundler/blob/master/typings/aurelia/aurelia-loader-default.d.ts#L3 - also import TemplateRegistryEntry

Typo in Proimise and Promse
https://github.com/cmichaelgraham/aurelia-amd-bundler/blob/master/typings/aurelia/aurelia-loader-default.d.ts#L6
https://github.com/cmichaelgraham/aurelia-amd-bundler/blob/master/typings/aurelia/aurelia-loader-default.d.ts#L7

**Comment by cmichaelgraham** [comment]
again, well done !!!! :+1: 

submitted PR: https://github.com/aurelia/loader-default/pull/20
