### ISSUE TITLE
Forgot to add CssAnimation interface

### ISSUE THREAD

**Issue by laurentiustamate94** [cmichaelgraham/aurelia-amd-bundler#3]
In file https://github.com/cmichaelgraham/aurelia-amd-bundler/blob/master/typings/aurelia/aurelia-animator-css.d.ts there is a compilation error at line 28 CssAnimation not found. Please fix this :)

**Comment by cmichaelgraham** [comment]
good catch !!  created this PR: https://github.com/aurelia/animator-css/pull/26
